### ISSUE TITLE
Not working for 8x8 grid LUT

### ISSUE THREAD

**Issue by Irfanlesnar** [zekierciyas/FancyFilter#1]
Why its not working for 8x8 grid LUT

This is my LUT which is 2D 8x8 grid. and its not working with the same code it shows pure red as output
![try_lut_3](https://github.com/zekierciyas/FancyFilter/assets/48024052/9f256154-a529-44b6-917e-0608296bddd2)

**Comment by zekierciyas** [comment]
The relevant LutProcessor was created to ensure that the effect is officially transferred only to 1*16 one-dimensional lutes.
